export const productCatalog = {
  EN: {
    hourLocale: "en-GB",
    motions: {
      discovery: "Discovery",
      qualification: "Qualification",
      closing: "Closing",
    },
    objections: {
      price: "Price",
      timing: "Timing",
      authority: "Authority",
      competitor: "Competitor",
      status_quo: "Status quo",
      trust: "Trust",
      other: "Other",
    },
    kindObjection: "Objection",
    kindObstacle: "Obstacle",
    kindUnknown: "Unclassified",
    resolutionResolved: "Resolved",
    resolutionOpen: "Open",
    resolutionUnknown: "Unknown",
    sampleLimited: "Fewer than five conversations is not enough for a conclusion.",
    unavailable: "Not available",
    briefNotReady: "The summary is not ready yet",
    briefReadFailed: "The summary could not be loaded",
    briefTitlePending: "Preparing the summary",
    briefTitlePartial: "Partial summary",
    briefTitleReady: "Conversation summary",
    briefTitleSkipped: "Nothing to summarize",
    briefTitleUnavailable: "Process not configured",
    briefTitleFailed: "The summary could not be completed",
    briefHighlightAt: "Highlighted at {hour}",
    briefAudioUnavailable: "Audio unavailable",
    briefPreparing: "Preparing…",
    coachingStrength: "Strength",
    coachingImprovement: "Improvement",
    coachingProcessHeading: "Process",
    coachingAdminMustPublish: "Your admin must publish the process.",
    coachingCrmOutcome: "CRM outcome: {outcome}",
    coachingViewCriteria: "View criteria and score",
    coachingSetupTitle: "Process not configured",
    coachingSetupAction: "Configure process",
    coachingWaitingTitle: "No score yet",
    coachingUnscoredTitle: "No score",
    objectionPlayableSpan: "Playable clip",
    noteSaveButton: "Save note",
    noteOffsetMeta: "{offset} ms · {author}",
    prospectQuote: "\"{quote}\"",
    objectionsNoneDetected: "No objections were found.",
    objectionsPartialAnalysis:
      "Part of the analysis is missing. We cannot claim there were no objections.",
    noteLabel: "Note",
    noteSaving: "Saving…",
    noteSaved: "Note saved",
    noteSaveFailed: "The note could not be saved",
    teamTitle: "Team",
    teamReadFailed: "The team insights could not be loaded",
    teamLoading: "Loading…",
    teamHeadingAdherence: "Adherence",
    teamHeadingObjections: "Objections",
    teamHeadingOutcomes: "Outcomes",
    teamHeadingActivity: "Activity",
    teamActivityAttempts: "Attempts",
    teamActivityConnected: "Conversations",
    teamActivityMeetings: "Meetings set",
    teamFilterRep: "Rep",
    teamFilterMotion: "Motion",
    teamFilterAllReps: "Whole team",
    teamFilterAllMotions: "All motions",
    teamResetFilters: "Reset filters",
    teamNoDataForFilters: "No data for these filters",
    teamDenied: "You cannot view the team",
    teamNewPanel: "The panel will fill in as your team logs interactions",
    teamUnresolvedAttribution: "Unresolved attribution",
    teamAdherenceMet: "Met",
    teamAdherenceApplicable: "Scorable",
    teamAdherenceEmpty: "No adherence",
    teamAdherenceOf: "{met} of {applicable}",
    checklistDone: "Done",
    teamOutcomesWon: "Won",
    teamOutcomesLost: "Lost",
    teamOutcomesRate: "Rate",
    teamObjectionsEmptyWeek: "No objections this week.",
    reportLoading: "Loading the report",
    reportFailed: "The report could not be loaded",
    meetingReadFailed: "The meeting could not be loaded",
    partialCrm: "Some CRM closes could not be loaded",
    briefHighlightHeading: "After the conversation",
    briefHighlightHelper:
      "The summary is generated as soon as the interaction ends. Choose when you want us to highlight it.",
    briefHighlightWhenAria: "When to highlight the summary",
    briefHighlightImmediate: "Immediate",
    briefHighlightDeferred30: "Delayed 30 minutes",
    briefHighlightEndOfDay: "End of day (18:00)",
    briefHighlightSaved: "Summary preference saved",
    briefHighlightSaveFailed: "The preference could not be saved",
    briefHighlightLoadFailed:
      "The preference could not be loaded. Try again later.",
    saveButton: "Save",
    callStartFailed: "Could not start the call.",
    callTokenStale: "The call session expired. Tap Call again.",
    callExtensionRestarted: "Vocify restarted. Tap Call again.",
    callSessionExpired: "Your Vocify session expired. Reload the extension.",
    callBusy: "Busy",
    callNoAnswer: "No answer",
    callCanceled: "Call canceled",
    callFailed: "Call failed",
    callRejected: "Call rejected",
    callHubSpotSearchFailed: "Could not search HubSpot",
    connect_crm: "Connect your CRM",
    history_partial: "Part of the history is missing",
    no_assigned: "No assigned contacts yet",
    none_now: "No priority contacts right now. Good time to prospect",
    retry: "Try again",
    map_owners: "Map owners",
    review_assignment: "Review your assignment with your admin",
    open_contacts: "Open contacts in CRM",
    title_connect_crm: "Connect your CRM to see who to contact",
    title_history_partial: "Part of the history is missing",
    title_no_assigned: "No assigned contacts to prioritize yet",
    title_none_now: "No priority contacts right now. Good time to prospect",
    scheduled_no_early_call: "Call agreed; do not call before then",
    pain_agree_next_step: "Confirmed the problem; agree the next step",
    agree_next_step: "Agree the next step",
    retry_read: "Retry the read",
    no_calls_logged: "No logged calls",
    log_first_call: "Log the first call",
    followup_pending: "Follow-up pending",
    resume_contact: "Resume the contact",
    priority_update_failed: "Could not refresh priorities",
    contactPrioritiesTitle: "Who to contact",
    contactPrioritiesLoading: "Reading the CRM…",
    contactPrioritiesStale: "Showing the last read.",
    today_incomplete: "Incomplete information",
    today_connect_title: "Connect your CRM to prepare your day",
    today_connect_admin_detail: "Your admin must connect the CRM.",
    today_prepare_failed: "Could not prepare your day",
    today_clear: "Nothing urgent today. Good time to prospect",
    today_no_activity: "No activity logged yet to prepare your day",
    dialVerifyBeforeCall: "Verify your number before calling",
    dialVerifyNumber: "Verify your number",
    dialToCallHint: "to call",
    dialContactNoPhone: "This contact has no phone",
    dialReadyToCall: "Ready to call",
    dialUnmuteMic: "Unmute microphone",
    dialMuteMic: "Mute",
    dialSearchPlaceholder: "Name, email or phone",
    dialNoPhone: "No phone",
    dialNoContactsTryAnother: "No contacts. Try another name.",
    dialTelnyxError: "Telnyx error",
    languageTitle: "Interface language",
    languageEnglish: "English",
    languageSpanish: "Spanish",
    settingsPageTitle: "Settings",
    settingsPageTitleBilling: "Billing",
    settingsNavAria: "Settings sections",
    settingsNavCrm: "CRM",
    settingsNavCalling: "Calling",
    settingsNavOffer: "Offer",
    settingsNavGlossary: "Glossary",
    settingsNavBrief: "Summaries",
    settingsNavPlaybooks: "Process",
    settingsNavTeam: "Team",
    settingsNavUsage: "Usage",
    settingsNavBilling: "Billing",
    offerSectionTitle: "Product & offer",
    offerSectionHelper:
      "What you sell, who it is for, and proof points. Used as reference when extracting call notes — it is not copied into CRM summaries. Owners and admins set this for the workspace.",
    offerPlaceholder: "Product, ICP, what you do not sell, proof points…",
    offerSaveButton: "Save offer",
    offerSaving: "Saving…",
    offerSavedToast: "Product context saved",
    offerSaveFailedToast: "Could not save product context",
    followupCopied: "Follow-up copied",
    followupEmailBodyCopied: "Email body copied: paste it into the draft",
    followupCompleteFailed: "Could not complete the follow-up",
    askConfirmFailed: "The confirmation could not be completed",
    askConfirmForContact: "Confirm for {contactId}",
    confirmAction: "Confirm",
    cancelAction: "Cancel",
    dismiss: "Dismiss",
    undo: "Undo",
    startCalling: "Start calling",
    queueSkip: "Skip",
    queueExit: "Exit",
    queueDone: "Done",
  },
  ES: {
    hourLocale: "es-ES",
    motions: {
      discovery: "Descubrimiento",
      qualification: "Calificación",
      closing: "Cierre",
    },
    objections: {
      price: "Precio",
      timing: "Plazo",
      authority: "Autoridad",
      competitor: "Competidor",
      status_quo: "Statu quo",
      trust: "Confianza",
      other: "Otra",
    },
    kindObjection: "Objeción",
    kindObstacle: "Obstáculo",
    kindUnknown: "Sin clasificar",
    resolutionResolved: "Resuelta",
    resolutionOpen: "Abierta",
    resolutionUnknown: "Sin dato",
    sampleLimited: "Con menos de cinco conversaciones no hay conclusión.",
    unavailable: "No disponible",
    briefNotReady: "El resumen todavía no está listo",
    briefReadFailed: "No se pudo leer el resumen",
    briefTitlePending: "Preparando el resumen",
    briefTitlePartial: "Resumen parcial",
    briefTitleReady: "Resumen de la conversación",
    briefTitleSkipped: "No hay conversación que resumir",
    briefTitleUnavailable: "Falta configurar el proceso",
    briefTitleFailed: "No se pudo completar el resumen",
    briefHighlightAt: "Se destaca a las {hour}",
    briefAudioUnavailable: "Audio no disponible",
    briefPreparing: "Preparando…",
    coachingStrength: "Fortaleza",
    coachingImprovement: "Mejora",
    coachingProcessHeading: "Proceso",
    coachingAdminMustPublish: "Tu administrador tiene que publicar el proceso.",
    coachingCrmOutcome: "Resultado en el CRM: {outcome}",
    coachingViewCriteria: "Ver criterios y nota",
    coachingSetupTitle: "Falta configurar el proceso",
    coachingSetupAction: "Configurar el proceso",
    coachingWaitingTitle: "Todavía no hay puntuación",
    coachingUnscoredTitle: "Sin puntuación",
    objectionPlayableSpan: "Tramo reproducible",
    noteSaveButton: "Guardar nota",
    noteOffsetMeta: "{offset} ms · {author}",
    prospectQuote: "«{quote}»",
    objectionsNoneDetected: "No se detectaron objeciones.",
    objectionsPartialAnalysis:
      "Falta parte del análisis. No se puede afirmar que no hubo objeciones.",
    noteLabel: "Nota",
    noteSaving: "Guardando…",
    noteSaved: "Nota guardada",
    noteSaveFailed: "No se pudo guardar la nota",
    teamTitle: "Equipo",
    teamReadFailed: "No se pudo leer el equipo",
    teamLoading: "Leyendo…",
    teamHeadingAdherence: "Adherencia",
    teamHeadingObjections: "Objeciones",
    teamHeadingOutcomes: "Resultados",
    teamHeadingActivity: "Actividad",
    teamActivityAttempts: "Intentos",
    teamActivityConnected: "Conversaciones",
    teamActivityMeetings: "Reuniones acordadas",
    teamFilterRep: "Comercial",
    teamFilterMotion: "Tipología",
    teamFilterAllReps: "Todo el equipo",
    teamFilterAllMotions: "Toda tipología",
    teamResetFilters: "Restablecer filtros",
    teamNoDataForFilters: "No hay datos para estos filtros",
    teamDenied: "No puedes ver el equipo",
    teamNewPanel: "El panel se completará con las interacciones de tu equipo",
    teamUnresolvedAttribution: "Sin atribución resuelta",
    teamAdherenceMet: "Cumplidos",
    teamAdherenceApplicable: "Evaluables",
    teamAdherenceEmpty: "Sin adherencia",
    teamAdherenceOf: "{met} de {applicable}",
    checklistDone: "Hecho",
    teamOutcomesWon: "Ganados",
    teamOutcomesLost: "Perdidos",
    teamOutcomesRate: "Tasa",
    teamObjectionsEmptyWeek: "No hay objeciones esta semana.",
    reportLoading: "Leyendo el informe",
    reportFailed: "No se pudo leer el informe",
    meetingReadFailed: "No se pudo leer la reunión",
    partialCrm: "Falta parte de los cierres del CRM",
    briefHighlightHeading: "Resumen posterior",
    briefHighlightHelper:
      "El resumen se genera en cuanto termina la interacción. Elige cuándo quieres que te lo destaquemos.",
    briefHighlightWhenAria: "Cuándo destacar el resumen",
    briefHighlightImmediate: "Inmediato",
    briefHighlightDeferred30: "Aplazado 30 minutos",
    briefHighlightEndOfDay: "Al final del día (18:00)",
    briefHighlightSaved: "Preferencia de resumen guardada",
    briefHighlightSaveFailed: "No se pudo guardar la preferencia",
    briefHighlightLoadFailed:
      "No se pudo cargar la preferencia. Inténtalo de nuevo más tarde.",
    saveButton: "Guardar",
    callStartFailed: "No se pudo iniciar la llamada.",
    callTokenStale: "La sesión de llamada caducó. Pulsa Llamar otra vez.",
    callExtensionRestarted: "Vocify se reinició. Pulsa Llamar otra vez.",
    callSessionExpired: "Tu sesión de Vocify caducó. Recarga la extensión.",
    callBusy: "Ocupado",
    callNoAnswer: "Sin respuesta",
    callCanceled: "Llamada cancelada",
    callFailed: "Llamada fallida",
    callRejected: "Llamada rechazada",
    callHubSpotSearchFailed: "No se pudo buscar en HubSpot",
    connect_crm: "Conectar CRM",
    history_partial: "Falta parte del historial",
    no_assigned: "Todavía no hay contactos asignados",
    none_now: "No hay contactos prioritarios ahora. Buen momento para prospectar",
    retry: "Reintentar",
    map_owners: "Mapear responsables",
    review_assignment: "Revisa tu asignación con el administrador",
    open_contacts: "Abrir contactos en CRM",
    title_connect_crm: "Conecta tu CRM para ver a quién contactar",
    title_history_partial: "Falta parte del historial",
    title_no_assigned: "Todavía no hay contactos asignados para priorizar",
    title_none_now: "No hay contactos prioritarios ahora. Buen momento para prospectar",
    scheduled_no_early_call: "Llamada acordada; no llamar antes",
    pain_agree_next_step: "Confirmó el problema; falta acordar el siguiente paso",
    agree_next_step: "Acordar el siguiente paso",
    retry_read: "Reintentar la lectura",
    no_calls_logged: "Sin llamadas registradas",
    log_first_call: "Registrar la primera llamada",
    followup_pending: "Seguimiento pendiente",
    resume_contact: "Retomar el contacto",
    priority_update_failed: "No se pudo actualizar la prioridad",
    contactPrioritiesTitle: "A quién contactar",
    contactPrioritiesLoading: "Leyendo el CRM…",
    contactPrioritiesStale: "Mostrando la última lectura.",
    today_incomplete: "Información incompleta",
    today_connect_title: "Conecta tu CRM para preparar tu día",
    today_connect_admin_detail: "Tu administrador tiene que conectar el CRM.",
    today_prepare_failed: "No se pudo preparar el día",
    today_clear: "Nada urgente hoy. Buen momento para prospectar",
    today_no_activity: "Todavía no hay actividad registrada para preparar tu día",
    dialVerifyBeforeCall: "Verifica tu número antes de llamar",
    dialVerifyNumber: "Verifica tu número",
    dialToCallHint: "para llamar",
    dialContactNoPhone: "Este contacto no tiene teléfono",
    dialReadyToCall: "Listo para llamar",
    dialUnmuteMic: "Activar micrófono",
    dialMuteMic: "Silenciar",
    dialSearchPlaceholder: "Nombre, email o teléfono",
    dialNoPhone: "Sin teléfono",
    dialNoContactsTryAnother: "Ningún contacto. Prueba otro nombre.",
    dialTelnyxError: "Error de Telnyx",
    languageTitle: "Idioma de la interfaz",
    languageEnglish: "Inglés",
    languageSpanish: "Español",
    settingsPageTitle: "Ajustes",
    settingsPageTitleBilling: "Facturación",
    settingsNavAria: "Secciones de ajustes",
    settingsNavCrm: "CRM",
    settingsNavCalling: "Llamadas",
    settingsNavOffer: "Oferta",
    settingsNavGlossary: "Glosario",
    settingsNavBrief: "Resúmenes",
    settingsNavPlaybooks: "Proceso",
    settingsNavTeam: "Equipo",
    settingsNavUsage: "Uso",
    settingsNavBilling: "Facturación",
    offerSectionTitle: "Producto y oferta",
    offerSectionHelper:
      "Qué vendes, para quién y pruebas de valor. Se usa como referencia al extraer notas de llamada; no se copia en los resúmenes del CRM. Lo configuran propietarios y administradores del espacio.",
    offerPlaceholder: "Producto, ICP, qué no vendes, pruebas de valor…",
    offerSaveButton: "Guardar oferta",
    offerSaving: "Guardando…",
    offerSavedToast: "Contexto de producto guardado",
    offerSaveFailedToast: "No se pudo guardar el contexto de producto",
    followupCopied: "Seguimiento copiado",
    followupEmailBodyCopied: "Cuerpo del correo copiado: pégalo en el borrador",
    followupCompleteFailed: "No se pudo completar el seguimiento",
    askConfirmFailed: "No se pudo completar la confirmación",
    askConfirmForContact: "Confirmar para {contactId}",
    confirmAction: "Confirmar",
    cancelAction: "Cancelar",
    dismiss: "Descartar",
    undo: "Deshacer",
    startCalling: "Empezar a llamar",
    queueSkip: "Saltar",
    queueExit: "Salir",
    queueDone: "Listo",
  },
} as const;

export type ProductTranslations = (typeof productCatalog)["EN"];

export function productText(
  key: string,
  catalog: ProductTranslations,
): string {
  if (key in catalog) {
    return catalog[key as keyof ProductTranslations] as string;
  }
  return key;
}

export function askConfirmPrompt(
  catalog: ProductTranslations,
  contactId: string,
): string {
  return catalog.askConfirmForContact.replace("{contactId}", contactId);
}
