export const productCatalog = {
  EN: {
    hourLocale: "en-GB",
    motions: {
      discovery: "Discovery",
      qualification: "Qualification",
      closing: "Closing",
    },
    objections: {
      price: "Price",
      timing: "Timing",
      authority: "Authority",
      competitor: "Competitor",
      status_quo: "Status quo",
      trust: "Trust",
      other: "Other",
    },
    kindObjection: "Objection",
    kindObstacle: "Obstacle",
    kindUnknown: "Unclassified",
    resolutionResolved: "Resolved",
    resolutionOpen: "Open",
    resolutionUnknown: "Unknown",
    sampleLimited: "Fewer than five conversations is not enough for a conclusion.",
    unavailable: "Not available",
    briefNotReady: "The summary is not ready yet",
    briefReadFailed: "The summary could not be loaded",
    briefTitlePending: "Preparing the summary",
    briefTitlePartial: "Partial summary",
    briefTitleReady: "Conversation summary",
    briefTitleSkipped: "Nothing to summarize",
    briefTitleUnavailable: "Process not configured",
    briefTitleFailed: "The summary could not be completed",
    briefHighlightAt: "Highlighted at {hour}",
    briefAudioUnavailable: "Audio unavailable",
    briefPreparing: "Preparing…",
    coachingStrength: "Strength",
    coachingImprovement: "Improvement",
    coachingProcessHeading: "Process",
    coachingAdminMustPublish: "Your admin must publish the process.",
    coachingCrmOutcome: "CRM outcome: {outcome}",
    coachingViewCriteria: "View criteria and score",
    coachingSetupTitle: "Process not configured",
    coachingSetupAction: "Configure process",
    coachingWaitingTitle: "No score yet",
    coachingUnscoredTitle: "No score",
    objectionPlayableSpan: "Playable clip",
    noteSaveButton: "Save note",
    noteOffsetMeta: "{offset} ms · {author}",
    prospectQuote: "\"{quote}\"",
    objectionsNoneDetected: "No objections were found.",
    objectionsPartialAnalysis:
      "Part of the analysis is missing. We cannot claim there were no objections.",
    noteLabel: "Note",
    noteSaving: "Saving…",
    noteSaved: "Note saved",
    noteSaveFailed: "The note could not be saved",
    teamTitle: "Team",
    teamReviewTitle: "To review",
    teamReadFailed: "The team insights could not be loaded",
    teamLoading: "Loading…",
    teamHeadingAdherence: "Adherence",
    teamHeadingObjections: "Objections",
    teamHeadingOutcomes: "Outcomes",
    teamHeadingActivity: "Activity",
    teamActivityAttempts: "Attempts",
    teamActivityConnected: "Conversations",
    teamActivityMeetings: "Meetings set",
    teamFilterRep: "Rep",
    teamFilterMotion: "Motion",
    teamFilterAllReps: "Whole team",
    teamFilterAllMotions: "All motions",
    teamResetFilters: "Reset filters",
    teamNoDataForFilters: "No data for these filters",
    teamDenied: "You cannot view the team",
    teamNewPanel: "The panel will fill in as your team logs interactions",
    teamUnresolvedAttribution: "Unresolved attribution",
    teamAdherenceMet: "Met",
    teamAdherenceApplicable: "Scorable",
    teamAdherenceEmpty: "No adherence",
    teamAdherenceOf: "{met} of {applicable}",
    teamTrendHeading: "Last {weeks} weeks",
    teamTrendDetail: "View detail",
    teamTrendWeek: "Week",
    teamTrendLegend: "Dotted: no conversations · Grey: not scored",
    teamTrendNoConversations: "No conversations",
    teamTrendEmpty: "No conversations in these weeks",
    teamTrendWithoutPlaybook: "{count} without process",
    teamTrendWithoutScore: "{count} not scored",
    teamTrendNoEvaluable: "No scorable steps",
    teamTrendNewVersion: "Process updated",
    teamTrendFailed: "The trend could not be loaded",
    checklistDone: "Done",
    teamOutcomesWon: "Won",
    teamOutcomesLost: "Lost",
    teamOutcomesRate: "Rate",
    teamObjectionsEmptyWeek: "No objections this week.",
    reportLoading: "Loading the report",
    reportFailed: "The report could not be loaded",
    meetingReadFailed: "The meeting could not be loaded",
    meetingBookedStage: "When a booked meeting is saved",
    meetingBookedStageNone: "Don't move the deal",
    partialCrm: "Some CRM closes could not be loaded",
    briefHighlightHeading: "After the conversation",
    briefHighlightHelper:
      "The summary is generated as soon as the interaction ends. Choose when you want us to highlight it.",
    briefHighlightWhenAria: "When to highlight the summary",
    briefHighlightImmediate: "Immediate",
    briefHighlightDeferred30: "Delayed 30 minutes",
    briefHighlightEndOfDay: "End of day (18:00)",
    briefHighlightSaved: "Summary preference saved",
    briefHighlightSaveFailed: "The preference could not be saved",
    briefHighlightLoadFailed:
      "The preference could not be loaded. Try again later.",
    writingSamplesHeading: "Your writing style",
    writingSamplesHelper: "Paste up to 3 of your emails so the draft sounds like you.",
    writingSamplesCountOne: "1 example",
    writingSamplesCountMany: "{count} examples",
    writingSamplesSlot: "Email {n}",
    writingSamplesTooShort: "Each email needs at least 40 characters.",
    writingSamplesSaved: "Examples saved",
    writingSamplesSaveFailed: "The examples could not be saved",
    writingSamplesLoadFailed: "The examples could not be loaded. Try again later.",
    saveButton: "Save",
    callStartFailed: "Could not start the call.",
    callTokenStale: "The call session expired. Tap Call again.",
    callExtensionRestarted: "Vocify restarted. Tap Call again.",
    callSessionExpired: "Your Vocify session expired. Reload the extension.",
    callBusy: "Busy",
    callNoAnswer: "No answer",
    callCanceled: "Call canceled",
    callFailed: "Call failed",
    callRejected: "Call rejected",
    callHubSpotSearchFailed: "Could not search HubSpot",
    connect_crm: "Connect your CRM",
    history_partial: "Part of the history is missing",
    no_assigned: "No assigned contacts yet",
    none_now: "No priority contacts right now. Good time to prospect",
    retry: "Try again",
    map_owners: "Map owners",
    review_assignment: "Review your assignment with your admin",
    open_contacts: "Open contacts in CRM",
    title_connect_crm: "Connect your CRM to see who to contact",
    title_history_partial: "Part of the history is missing",
    title_no_assigned: "No assigned contacts to prioritize yet",
    title_none_now: "No priority contacts right now. Good time to prospect",
    scheduled_no_early_call: "Call agreed; do not call before then",
    pain_agree_next_step: "Confirmed the problem; agree the next step",
    agree_next_step: "Agree the next step",
    retry_read: "Retry the read",
    no_calls_logged: "No logged calls",
    log_first_call: "Log the first call",
    followup_pending: "Follow-up pending",
    resume_contact: "Resume the contact",
    priority_update_failed: "Could not refresh priorities",
    contactPrioritiesTitle: "Who to contact",
    contactPrioritiesLoading: "Reading the CRM…",
    contactPrioritiesStale: "Showing the last read.",
    today_incomplete: "Incomplete information",
    today_connect_title: "Connect your CRM to prepare your day",
    today_connect_admin_detail: "Your admin must connect the CRM.",
    today_prepare_failed: "Could not prepare your day",
    today_clear: "Nothing urgent today. Good time to prospect",
    today_no_activity: "No activity logged yet to prepare your day",
    today_record: "Record an interaction",
    today_folded: "{count} more",
    today_open: "Open in CRM",
    today_call: "Call",
    today_calls: "From your conversations",
    today_tasks: "CRM tasks",
    today_task_kind: "CRM task",
    today_tasks_in_crm: "Open tasks in CRM ({count} more)",
    today_capture: "Record interaction",
    today_unknown_contact: "Contact",
    today_origin_manual: "CRM task",
    today_origin_detected: "Detected",
    today_origin_both: "CRM task and detected",
    today_details: "Details",
    today_signal_commitment: "Commitment",
    today_signal_cold: "Going cold",
    today_signal_objection: "Open objection",
    today_signal_no_reply: "No reply",
    today_signal_pain: "Confirmed pain",
    today_signal_uncalled: "Not called yet",
    home_meetings: "Today's meetings",
    home_needs_ok: "Needs your OK",
    home_calls: "Who to call",
    home_upcoming: "Coming up",
    home_done: "Done today",
    home_folded: "{count} more once these are done",
    home_in_crm: "In the CRM",
    home_pulse_calls: "{count} calls today",
    home_pulse_call: "1 call today",
    home_pulse_calls_saved: "{count} calls today, all saved to {crm}",
    home_pulse_call_saved: "1 call today, saved to {crm}",
    home_followup_row: "Follow-up for {name}",
    home_followup_subject: "“{subject}”",
    home_followup_writing: "Writing the follow-up…",
    home_followup_failed: "Could not draft it",
    home_review_row: "Conversation with {name} not saved to the CRM",
    home_confirm_group: "{count} confirmations pending",
    home_open: "Open",
    home_review: "Review",
    home_meeting_no_time: "Today · no time set",
    home_card_dismissed: "Dismissed",
    home_card_snoozed: "Snoozed",
    panel_before_call: "Before you call",
    panel_history: "Conversations",
    panel_followup_pending: "Follow-up pending",
    panel_followup_ready: "ready",
    panel_call: "Call {name}",
    panel_in_call: "On a call",
    panel_hang_up: "Hang up",
    panel_processing: "Processing the call…",
    panel_saved: "✓ Saved to {crm}",
    panel_review_save: "Review and save",
    panel_no_answer: "No answer · {time}",
    panel_next: "Next: {name}",
    panel_call_failed: "Call failed",
    panel_call_duration_saved: "Call · {minutes} min · ✓ Saved to {crm}",
    panel_call_duration: "Call · {minutes} min",
    panel_followup: "Follow-up",
    panel_snooze: "Snooze until tomorrow",
    panel_meeting_today: "Meeting today {time}",
    panel_contact_sheet: "Contact",
    panel_brief_failed: "Could not load everything.",
    panel_kind_call: "Call",
    panel_kind_meeting: "Meeting",
    panel_kind_visit: "Visit",
    panel_kind_conversation: "Conversation",
    panel_minutes: "{count} min",
    done_call: "Call with {name}",
    done_followup: "Follow-up sent to {name}",
    done_signal: "Resolved: {name}",
    done_confirmed: "Confirmed: {what}",
    dialVerifyBeforeCall: "Verify your number before calling",
    dialVerifyNumber: "Verify your number",
    dialToCallHint: "to call",
    dialContactNoPhone: "This contact has no phone",
    dialReadyToCall: "Ready to call",
    dialUnmuteMic: "Unmute microphone",
    dialMuteMic: "Mute",
    dialSearchPlaceholder: "Name, email or phone",
    dialNoPhone: "No phone",
    dialNoContactsTryAnother: "No contacts. Try another name.",
    dialTelnyxError: "Telnyx error",
    languageTitle: "Interface language",
    languageEnglish: "English",
    languageSpanish: "Spanish",
    settingsPageTitle: "Settings",
    settingsPageTitleBilling: "Billing",
    settingsNavAria: "Settings sections",
    settingsNavCrm: "CRM",
    settingsNavCalling: "Calling",
    settingsNavOffer: "Offer",
    settingsNavGlossary: "Glossary",
    settingsNavBrief: "Summaries",
    settingsNavPlaybooks: "Process",
    settingsNavTeam: "Team",
    settingsNavUsage: "Usage",
    settingsNavBilling: "Billing",
    offerSectionTitle: "Product & offer",
    offerSectionHelper:
      "What you sell, who it is for, and proof points. Used as reference when extracting call notes — it is not copied into CRM summaries. Owners and admins set this for the workspace.",
    offerPlaceholder: "Product, ICP, what you do not sell, proof points…",
    offerSaveButton: "Save offer",
    offerSaving: "Saving…",
    offerSavedToast: "Product context saved",
    offerSaveFailedToast: "Could not save product context",
    followupCopied: "Follow-up copied",
    followupEmailBodyCopied: "Email body copied: paste it into the draft",
    followupCompleteFailed: "Could not complete the follow-up",
    askConfirmFailed: "The confirmation could not be completed",
    askConfirmForContact: "Confirm for {contactId}",
    confirmAction: "Confirm",
    cancelAction: "Cancel",
    dismiss: "Dismiss",
    undo: "Undo",
    startCalling: "Start calling",
    queueSkip: "Skip",
    queueExit: "Exit",
    queueDone: "Done",
    todayTitle: "Today",
    askTitle: "Ask",
    askUnread: "There's a new reply",
    askChoicesLabel: "Options",
    askPlaceholder: "Ask about a contact",
    askSend: "Send",
    askRecord: "Record",
    askStop: "Stop",
    askRecording: "Recording {seconds}s",
    askTranscribing: "Transcribing",
    askNoMic: "No microphone. You can type the question.",
    askEmpty: "Ask about a contact, or about what happened in the last conversation.",
    askForbidden: "Permission is missing to read that part of the CRM.",
    askPartial: "Only part of it was read. The result is incomplete.",
    askUnavailable: "The CRM could not be read. You can try again.",
    askNoResults: "No results for this question.",
    navHome: "Home",
    navToday: "Today",
    navMemos: "Voice Memos",
    navConversations: "Conversations",
    navCopilot: "Call Copilot",
    navAsk: "Ask",
    navSettings: "Settings",
    navInsights: "Team",
    navCall: "Call",
    navLogOut: "Log out",
    navPlans: "Plans",
    navScale: "Scale with us",
    navPlansBody: "Starter captures the call. Pro puts you on the line.",
    navScaleBody: "Unlimited memos and multi-CRM sync.",
    navManageBilling: "Manage billing",
    navChoosePlan: "Choose a plan",
    navBookDemo: "Book a demo",
    reportTitle: "Report",
    reportUnread: "{count} unread reports",
    reportsLabel: "Reports",
    reportTitleDaily: "Your day",
    reportTitleWeekly: "Your week",
    reportTitleTeam: "Your team this week",
    reportGeneratedAt: "Generated {date}",
    reportAdherenceSteps: "{met} of {applicable} steps",
    reportByDay: "By day",
    reportDay: "Day",
    reportDayNotIncluded: "Not included",
    reportAdherenceByWeek: "Adherence by week",
    reportTrendUnscored: "Not scored",
    reportTrendSampleNote: "* Fewer than five scored conversations: no conclusion.",
    reportTopObjections: "Most frequent objections",
    reportChannelCallOne: "1 call",
    reportChannelCallOther: "{count} calls",
    reportChannelMeetingOne: "1 meeting",
    reportChannelMeetingOther: "{count} meetings",
    reportChannelVisitOne: "1 visit",
    reportChannelVisitOther: "{count} visits",
    reportConfigure: "Set up my reports",
    reportPrefDaily: "Daily summary by email",
    reportPrefWeekly: "Weekly summary on Fridays",
    reportPrefTeam: "Team report on Fridays",
    reportPrefSaveFailed: "Could not save the change.",
    bellEmpty: "No reports yet",
    bellVocifyDid: "Vocify did",
    bellCrmUpdated: "CRM updated: {resources}",
    bellMeetingStage: "Deal moved to the meeting booked stage",
    bellBecause: "From your conversation with {subject}",
    bellBecauseUnnamed: "From one of your conversations",
    listAnd: "and",
    crmResources: {
      deal: "deal",
      contact: "contact",
      company: "company",
      task: "tasks",
      note: "note",
      line_item: "line items",
    },
    playbookTitle: "Sales process",
    playbookStatusMissing: "No published process",
    playbookStatusDraft: "Draft",
    playbookStatusImporting: "Preparing content",
    playbookStatusPublished: "Active",
    playbookNewTypePlaceholder: "New motion",
    playbookAddType: "Add motion",
    playbookImportIdPlaceholder: "Import ID",
    playbookResumeImport: "Continue import",
    playbookVersion: "version {id}",
    playbookPastePlaceholder: "Paste how you sell in this motion",
    playbookSaveDraft: "Save draft",
    playbookImportPdf: "Import PDF",
    playbookPublish: "Publish",
    playbookStepChoose: "Choose a motion",
    playbookStepProvide: "Add text, a PDF, or audio",
    playbookStepReview: "Review",
    playbookStepPublish: "Publish",
    playbookNoticeAdmin: "Your admin must configure the process.",
    playbookNoticeStart: "Define your process to turn coaching on.",
    playbookNoticeDraft: "You have a playbook waiting to be published.",
    playbookNoticeMissing: "The remaining motions still need a published process.",
    playbookPdfEncrypted: "The PDF is protected. Paste the text or upload a file without a password.",
    playbookPdfNoText: "The PDF has no text. Try another file or paste the text.",
    playbookImportFailed: "The import failed.",
    playbookContradiction: "Some steps contradict each other. Edit the draft before publishing.",
    homeWelcome: "Welcome back,",
    homeReady: "Ready to update your CRM?",
    capturePaste: "Paste transcript",
    capturePastePlaceholder: "Paste your transcript text here...",
    captureImport: "Import and extract",
    captureImporting: "Importing…",
    recentTitle: "Recent",
    activityViewAll: "View all",
    activityRecordingsFailed: "Could not load recordings.",
    activityCheckCrm: "Check CRM settings",
    activityLoading: "Loading activity…",
    activityKindRecording: "Recording",
    activityKindMemo: "Memo",
    activityShow: "Show",
    activityMine: "Mine",
    activityAll: "All",
    askExample: "What is still pending with this contact?",
    askSending: "Sending…",
    askConsulting: "Reading the CRM…",
    askStillGoing: "Still working. You can close this and come back.",
    askPhasePartial: "Only part of the CRM was read.",
  },
  ES: {
    hourLocale: "es-ES",
    motions: {
      discovery: "Descubrimiento",
      qualification: "Calificación",
      closing: "Cierre",
    },
    objections: {
      price: "Precio",
      timing: "Plazo",
      authority: "Autoridad",
      competitor: "Competidor",
      status_quo: "Statu quo",
      trust: "Confianza",
      other: "Otra",
    },
    kindObjection: "Objeción",
    kindObstacle: "Obstáculo",
    kindUnknown: "Sin clasificar",
    resolutionResolved: "Resuelta",
    resolutionOpen: "Abierta",
    resolutionUnknown: "Sin dato",
    sampleLimited: "Con menos de cinco conversaciones no hay conclusión.",
    unavailable: "No disponible",
    briefNotReady: "El resumen todavía no está listo",
    briefReadFailed: "No se pudo leer el resumen",
    briefTitlePending: "Preparando el resumen",
    briefTitlePartial: "Resumen parcial",
    briefTitleReady: "Resumen de la conversación",
    briefTitleSkipped: "No hay conversación que resumir",
    briefTitleUnavailable: "Falta configurar el proceso",
    briefTitleFailed: "No se pudo completar el resumen",
    briefHighlightAt: "Se destaca a las {hour}",
    briefAudioUnavailable: "Audio no disponible",
    briefPreparing: "Preparando…",
    coachingStrength: "Fortaleza",
    coachingImprovement: "Mejora",
    coachingProcessHeading: "Proceso",
    coachingAdminMustPublish: "Tu administrador tiene que publicar el proceso.",
    coachingCrmOutcome: "Resultado en el CRM: {outcome}",
    coachingViewCriteria: "Ver criterios y nota",
    coachingSetupTitle: "Falta configurar el proceso",
    coachingSetupAction: "Configurar el proceso",
    coachingWaitingTitle: "Todavía no hay puntuación",
    coachingUnscoredTitle: "Sin puntuación",
    objectionPlayableSpan: "Tramo reproducible",
    noteSaveButton: "Guardar nota",
    noteOffsetMeta: "{offset} ms · {author}",
    prospectQuote: "«{quote}»",
    objectionsNoneDetected: "No se detectaron objeciones.",
    objectionsPartialAnalysis:
      "Falta parte del análisis. No se puede afirmar que no hubo objeciones.",
    noteLabel: "Nota",
    noteSaving: "Guardando…",
    noteSaved: "Nota guardada",
    noteSaveFailed: "No se pudo guardar la nota",
    teamTitle: "Equipo",
    teamReviewTitle: "Para revisar",
    teamReadFailed: "No se pudo leer el equipo",
    teamLoading: "Leyendo…",
    teamHeadingAdherence: "Adherencia",
    teamHeadingObjections: "Objeciones",
    teamHeadingOutcomes: "Resultados",
    teamHeadingActivity: "Actividad",
    teamActivityAttempts: "Intentos",
    teamActivityConnected: "Conversaciones",
    teamActivityMeetings: "Reuniones acordadas",
    teamFilterRep: "Comercial",
    teamFilterMotion: "Tipología",
    teamFilterAllReps: "Todo el equipo",
    teamFilterAllMotions: "Toda tipología",
    teamResetFilters: "Restablecer filtros",
    teamNoDataForFilters: "No hay datos para estos filtros",
    teamDenied: "No puedes ver el equipo",
    teamNewPanel: "El panel se completará con las interacciones de tu equipo",
    teamUnresolvedAttribution: "Sin atribución resuelta",
    teamAdherenceMet: "Cumplidos",
    teamAdherenceApplicable: "Evaluables",
    teamAdherenceEmpty: "Sin adherencia",
    teamAdherenceOf: "{met} de {applicable}",
    teamTrendHeading: "Últimas {weeks} semanas",
    teamTrendDetail: "Ver detalle",
    teamTrendWeek: "Semana",
    teamTrendLegend: "Punteado: sin conversaciones · Gris: sin puntuar",
    teamTrendNoConversations: "Sin conversaciones",
    teamTrendEmpty: "Sin conversaciones en estas semanas",
    teamTrendWithoutPlaybook: "{count} sin proceso",
    teamTrendWithoutScore: "{count} sin puntuar",
    teamTrendNoEvaluable: "Sin pasos evaluables",
    teamTrendNewVersion: "Proceso actualizado",
    teamTrendFailed: "No se pudo cargar la evolución",
    checklistDone: "Hecho",
    teamOutcomesWon: "Ganados",
    teamOutcomesLost: "Perdidos",
    teamOutcomesRate: "Tasa",
    teamObjectionsEmptyWeek: "No hay objeciones esta semana.",
    reportLoading: "Leyendo el informe",
    reportFailed: "No se pudo leer el informe",
    meetingReadFailed: "No se pudo leer la reunión",
    meetingBookedStage: "Al guardar una reunión acordada",
    meetingBookedStageNone: "No mover el deal",
    partialCrm: "Falta parte de los cierres del CRM",
    briefHighlightHeading: "Resumen posterior",
    briefHighlightHelper:
      "El resumen se genera en cuanto termina la interacción. Elige cuándo quieres que te lo destaquemos.",
    briefHighlightWhenAria: "Cuándo destacar el resumen",
    briefHighlightImmediate: "Inmediato",
    briefHighlightDeferred30: "Aplazado 30 minutos",
    briefHighlightEndOfDay: "Al final del día (18:00)",
    briefHighlightSaved: "Preferencia de resumen guardada",
    briefHighlightSaveFailed: "No se pudo guardar la preferencia",
    briefHighlightLoadFailed:
      "No se pudo cargar la preferencia. Inténtalo de nuevo más tarde.",
    writingSamplesHeading: "Tu forma de escribir",
    writingSamplesHelper: "Pega hasta 3 emails tuyos para que el borrador suene a ti.",
    writingSamplesCountOne: "1 ejemplo",
    writingSamplesCountMany: "{count} ejemplos",
    writingSamplesSlot: "Email {n}",
    writingSamplesTooShort: "Cada email necesita al menos 40 caracteres.",
    writingSamplesSaved: "Ejemplos guardados",
    writingSamplesSaveFailed: "No se pudieron guardar los ejemplos",
    writingSamplesLoadFailed: "No se pudieron cargar los ejemplos. Inténtalo de nuevo más tarde.",
    saveButton: "Guardar",
    callStartFailed: "No se pudo iniciar la llamada.",
    callTokenStale: "La sesión de llamada caducó. Pulsa Llamar otra vez.",
    callExtensionRestarted: "Vocify se reinició. Pulsa Llamar otra vez.",
    callSessionExpired: "Tu sesión de Vocify caducó. Recarga la extensión.",
    callBusy: "Ocupado",
    callNoAnswer: "Sin respuesta",
    callCanceled: "Llamada cancelada",
    callFailed: "Llamada fallida",
    callRejected: "Llamada rechazada",
    callHubSpotSearchFailed: "No se pudo buscar en HubSpot",
    connect_crm: "Conectar CRM",
    history_partial: "Falta parte del historial",
    no_assigned: "Todavía no hay contactos asignados",
    none_now: "No hay contactos prioritarios ahora. Buen momento para prospectar",
    retry: "Reintentar",
    map_owners: "Mapear responsables",
    review_assignment: "Revisa tu asignación con el administrador",
    open_contacts: "Abrir contactos en CRM",
    title_connect_crm: "Conecta tu CRM para ver a quién contactar",
    title_history_partial: "Falta parte del historial",
    title_no_assigned: "Todavía no hay contactos asignados para priorizar",
    title_none_now: "No hay contactos prioritarios ahora. Buen momento para prospectar",
    scheduled_no_early_call: "Llamada acordada; no llamar antes",
    pain_agree_next_step: "Confirmó el problema; falta acordar el siguiente paso",
    agree_next_step: "Acordar el siguiente paso",
    retry_read: "Reintentar la lectura",
    no_calls_logged: "Sin llamadas registradas",
    log_first_call: "Registrar la primera llamada",
    followup_pending: "Seguimiento pendiente",
    resume_contact: "Retomar el contacto",
    priority_update_failed: "No se pudo actualizar la prioridad",
    contactPrioritiesTitle: "A quién contactar",
    contactPrioritiesLoading: "Leyendo el CRM…",
    contactPrioritiesStale: "Mostrando la última lectura.",
    today_incomplete: "Información incompleta",
    today_connect_title: "Conecta tu CRM para preparar tu día",
    today_connect_admin_detail: "Tu administrador tiene que conectar el CRM.",
    today_prepare_failed: "No se pudo preparar el día",
    today_clear: "Nada urgente hoy. Buen momento para prospectar",
    today_no_activity: "Todavía no hay actividad registrada para preparar tu día",
    today_record: "Grabar una interacción",
    today_folded: "{count} más",
    today_open: "Abrir en el CRM",
    today_call: "Llamar",
    today_calls: "De tus conversaciones",
    today_tasks: "Tareas del CRM",
    today_task_kind: "Tarea del CRM",
    today_tasks_in_crm: "Ver tareas en el CRM ({count} más)",
    today_capture: "Grabar interacción",
    today_unknown_contact: "Contacto",
    today_origin_manual: "Tarea del CRM",
    today_origin_detected: "Detectada",
    today_origin_both: "Tarea del CRM y detectada",
    today_details: "Detalle",
    today_signal_commitment: "Compromiso",
    today_signal_cold: "Enfriamiento",
    today_signal_objection: "Objeción abierta",
    today_signal_no_reply: "Sin respuesta",
    today_signal_pain: "Dolor confirmado",
    today_signal_uncalled: "Sin llamar",
    home_meetings: "Reuniones de hoy",
    home_needs_ok: "Falta tu OK",
    home_calls: "A quién llamar",
    home_upcoming: "Próximas",
    home_done: "Hecho hoy",
    home_folded: "{count} más cuando termines estos",
    home_in_crm: "En el CRM",
    home_pulse_calls: "{count} llamadas hoy",
    home_pulse_call: "1 llamada hoy",
    home_pulse_calls_saved: "{count} llamadas hoy, todas guardadas en {crm}",
    home_pulse_call_saved: "1 llamada hoy, guardada en {crm}",
    home_followup_row: "Follow-up para {name}",
    home_followup_subject: "«{subject}»",
    home_followup_writing: "Escribiendo el seguimiento…",
    home_followup_failed: "No se pudo redactar",
    home_review_row: "Conversación con {name} sin guardar en el CRM",
    home_confirm_group: "{count} confirmaciones pendientes",
    home_open: "Abrir",
    home_review: "Revisar",
    home_meeting_no_time: "Hoy · sin hora",
    home_card_dismissed: "Descartada",
    home_card_snoozed: "Pospuesta",
    panel_before_call: "Antes de llamar",
    panel_history: "Conversaciones",
    panel_followup_pending: "Follow-up pendiente",
    panel_followup_ready: "listo",
    panel_call: "Llamar a {name}",
    panel_in_call: "En llamada",
    panel_hang_up: "Colgar",
    panel_processing: "Procesando la llamada…",
    panel_saved: "✓ Guardado en {crm}",
    panel_review_save: "Revisar y guardar",
    panel_no_answer: "Sin respuesta · {time}",
    panel_next: "Siguiente: {name}",
    panel_call_failed: "Llamada fallida",
    panel_call_duration_saved: "Llamada de {minutes} min · ✓ Guardado en {crm}",
    panel_call_duration: "Llamada de {minutes} min",
    panel_followup: "Follow-up",
    panel_snooze: "Posponer a mañana",
    panel_meeting_today: "Reunión hoy {time}",
    panel_contact_sheet: "Contacto",
    panel_brief_failed: "No se pudo cargar todo.",
    panel_kind_call: "Llamada",
    panel_kind_meeting: "Reunión",
    panel_kind_visit: "Visita",
    panel_kind_conversation: "Conversación",
    panel_minutes: "{count} min",
    done_call: "Llamada con {name}",
    done_followup: "Follow-up enviado a {name}",
    done_signal: "Resuelto: {name}",
    done_confirmed: "Confirmado: {what}",
    dialVerifyBeforeCall: "Verifica tu número antes de llamar",
    dialVerifyNumber: "Verifica tu número",
    dialToCallHint: "para llamar",
    dialContactNoPhone: "Este contacto no tiene teléfono",
    dialReadyToCall: "Listo para llamar",
    dialUnmuteMic: "Activar micrófono",
    dialMuteMic: "Silenciar",
    dialSearchPlaceholder: "Nombre, email o teléfono",
    dialNoPhone: "Sin teléfono",
    dialNoContactsTryAnother: "Ningún contacto. Prueba otro nombre.",
    dialTelnyxError: "Error de Telnyx",
    languageTitle: "Idioma de la interfaz",
    languageEnglish: "Inglés",
    languageSpanish: "Español",
    settingsPageTitle: "Ajustes",
    settingsPageTitleBilling: "Facturación",
    settingsNavAria: "Secciones de ajustes",
    settingsNavCrm: "CRM",
    settingsNavCalling: "Llamadas",
    settingsNavOffer: "Oferta",
    settingsNavGlossary: "Glosario",
    settingsNavBrief: "Resúmenes",
    settingsNavPlaybooks: "Proceso",
    settingsNavTeam: "Equipo",
    settingsNavUsage: "Uso",
    settingsNavBilling: "Facturación",
    offerSectionTitle: "Producto y oferta",
    offerSectionHelper:
      "Qué vendes, para quién y pruebas de valor. Se usa como referencia al extraer notas de llamada; no se copia en los resúmenes del CRM. Lo configuran propietarios y administradores del espacio.",
    offerPlaceholder: "Producto, ICP, qué no vendes, pruebas de valor…",
    offerSaveButton: "Guardar oferta",
    offerSaving: "Guardando…",
    offerSavedToast: "Contexto de producto guardado",
    offerSaveFailedToast: "No se pudo guardar el contexto de producto",
    followupCopied: "Seguimiento copiado",
    followupEmailBodyCopied: "Cuerpo del correo copiado: pégalo en el borrador",
    followupCompleteFailed: "No se pudo completar el seguimiento",
    askConfirmFailed: "No se pudo completar la confirmación",
    askConfirmForContact: "Confirmar para {contactId}",
    confirmAction: "Confirmar",
    cancelAction: "Cancelar",
    dismiss: "Descartar",
    undo: "Deshacer",
    startCalling: "Empezar a llamar",
    queueSkip: "Saltar",
    queueExit: "Salir",
    queueDone: "Listo",
    todayTitle: "Hoy",
    askTitle: "Preguntar",
    askUnread: "Hay una respuesta nueva",
    askChoicesLabel: "Opciones",
    askPlaceholder: "Pregunta por un contacto",
    askSend: "Enviar",
    askRecord: "Grabar",
    askStop: "Detener",
    askRecording: "Grabando {seconds}s",
    askTranscribing: "Transcribiendo",
    askNoMic: "Sin micrófono. Puedes escribir la pregunta.",
    askEmpty: "Pregunta por un contacto o por lo que pasó en la última conversación.",
    askForbidden: "Falta permiso para leer esa parte del CRM.",
    askPartial: "Solo se ha leído una parte. El resultado no está completo.",
    askUnavailable: "No se ha podido leer el CRM. Puedes reintentar.",
    askNoResults: "No hay resultados para esta consulta.",
    navHome: "Inicio",
    navToday: "Hoy",
    navMemos: "Notas de voz",
    navConversations: "Conversaciones",
    navCopilot: "Copiloto",
    navAsk: "Preguntar",
    navSettings: "Ajustes",
    navInsights: "Equipo",
    navCall: "Llamar",
    navLogOut: "Salir",
    navPlans: "Planes",
    navScale: "Escala con nosotros",
    navPlansBody: "Starter captura la llamada. Pro te pone en la línea.",
    navScaleBody: "Notas ilimitadas y sincronización con varios CRM.",
    navManageBilling: "Gestionar facturación",
    navChoosePlan: "Elegir un plan",
    navBookDemo: "Reservar una demo",
    reportTitle: "Informe",
    reportUnread: "{count} informes sin leer",
    reportsLabel: "Informes",
    reportTitleDaily: "Tu resumen del día",
    reportTitleWeekly: "Tu semana",
    reportTitleTeam: "Tu equipo esta semana",
    reportGeneratedAt: "Generado el {date}",
    reportAdherenceSteps: "{met} de {applicable} pasos",
    reportByDay: "Por día",
    reportDay: "Día",
    reportDayNotIncluded: "No incluido",
    reportAdherenceByWeek: "Adherencia por semana",
    reportTrendUnscored: "Sin puntuar",
    reportTrendSampleNote: "* Menos de cinco conversaciones puntuadas: sin conclusión.",
    reportTopObjections: "Objeciones más frecuentes",
    reportChannelCallOne: "1 llamada",
    reportChannelCallOther: "{count} llamadas",
    reportChannelMeetingOne: "1 reunión",
    reportChannelMeetingOther: "{count} reuniones",
    reportChannelVisitOne: "1 visita",
    reportChannelVisitOther: "{count} visitas",
    reportConfigure: "Configurar mis informes",
    reportPrefDaily: "Resumen diario por email",
    reportPrefWeekly: "Resumen semanal los viernes",
    reportPrefTeam: "Informe de equipo los viernes",
    reportPrefSaveFailed: "No se pudo guardar el cambio.",
    bellEmpty: "Aún no hay informes",
    bellVocifyDid: "Vocify hizo",
    bellCrmUpdated: "CRM actualizado: {resources}",
    bellMeetingStage: "Deal movido a la etapa de reunión agendada",
    bellBecause: "Por tu conversación con {subject}",
    bellBecauseUnnamed: "Por una de tus conversaciones",
    listAnd: "y",
    crmResources: {
      deal: "deal",
      contact: "contacto",
      company: "empresa",
      task: "tareas",
      note: "nota",
      line_item: "líneas de producto",
    },
    playbookTitle: "Proceso comercial",
    playbookStatusMissing: "Sin proceso publicado",
    playbookStatusDraft: "Borrador",
    playbookStatusImporting: "Preparando contenido",
    playbookStatusPublished: "Activo",
    playbookNewTypePlaceholder: "Nueva tipología",
    playbookAddType: "Añadir tipología",
    playbookImportIdPlaceholder: "ID de importación",
    playbookResumeImport: "Continuar importación",
    playbookVersion: "versión {id}",
    playbookPastePlaceholder: "Pega cómo vendéis en esta tipología",
    playbookSaveDraft: "Guardar borrador",
    playbookImportPdf: "Importar PDF",
    playbookPublish: "Publicar",
    playbookStepChoose: "Elegir tipología",
    playbookStepProvide: "Aportar texto, PDF o audio",
    playbookStepReview: "Revisar",
    playbookStepPublish: "Publicar",
    playbookNoticeAdmin: "Tu administrador debe configurar el proceso.",
    playbookNoticeStart: "Define vuestro proceso para activar el coaching.",
    playbookNoticeDraft: "Tienes un playbook pendiente de publicar.",
    playbookNoticeMissing: "Falta publicar el proceso de las tipologías pendientes.",
    playbookPdfEncrypted: "El PDF está protegido. Pega el texto o sube un archivo sin contraseña.",
    playbookPdfNoText: "El PDF no tiene texto. Prueba con otro archivo o pega el texto.",
    playbookImportFailed: "No se ha podido importar.",
    playbookContradiction: "Hay pasos contradictorios. Edita el borrador antes de publicar.",
    homeWelcome: "Hola de nuevo,",
    homeReady: "¿Listo para actualizar el CRM?",
    capturePaste: "Pegar transcripción",
    capturePastePlaceholder: "Pega aquí la transcripción…",
    captureImport: "Importar y extraer",
    captureImporting: "Importando…",
    recentTitle: "Recientes",
    activityViewAll: "Ver todo",
    activityRecordingsFailed: "No se pudieron leer las grabaciones.",
    activityCheckCrm: "Revisar el CRM",
    activityLoading: "Leyendo la actividad…",
    activityKindRecording: "Grabación",
    activityKindMemo: "Nota",
    activityShow: "Ver",
    activityMine: "Mías",
    activityAll: "Todas",
    askExample: "¿Qué quedó pendiente con este contacto?",
    askSending: "Enviando…",
    askConsulting: "Leyendo el CRM…",
    askStillGoing: "Sigue en curso. Puedes cerrar y volver.",
    askPhasePartial: "Solo se leyó una parte del CRM.",
  },
} as const;

export type ProductTranslations = (typeof productCatalog)["EN"];

export function productText(
  key: string,
  catalog: ProductTranslations,
): string {
  if (key in catalog) {
    return catalog[key as keyof ProductTranslations] as string;
  }
  return key;
}

export function askConfirmPrompt(
  catalog: ProductTranslations,
  contactId: string,
): string {
  return catalog.askConfirmForContact.replace("{contactId}", contactId);
}
