export const productCatalog = {
  EN: {
    motions: {
      discovery: "Discovery",
      qualification: "Qualification",
      closing: "Closing",
    },
    objections: {
      price: "Price",
      timing: "Timing",
      authority: "Authority",
      competitor: "Competitor",
      status_quo: "Status quo",
      trust: "Trust",
      other: "Other",
    },
    kindObjection: "Objection",
    kindObstacle: "Obstacle",
    kindUnknown: "Unclassified",
    resolutionResolved: "Resolved",
    resolutionOpen: "Open",
    resolutionUnknown: "Unknown",
    sampleLimited: "Fewer than five conversations is not enough for a conclusion.",
    unavailable: "Not available",
    briefNotReady: "The summary is not ready yet",
    briefReadFailed: "The summary could not be loaded",
    reportLoading: "Loading the report",
    reportFailed: "The report could not be loaded",
    meetingReadFailed: "The meeting could not be loaded",
    partialCrm: "Some CRM closes could not be loaded",
  },
  ES: {
    motions: {
      discovery: "Descubrimiento",
      qualification: "Calificación",
      closing: "Cierre",
    },
    objections: {
      price: "Precio",
      timing: "Plazo",
      authority: "Autoridad",
      competitor: "Competidor",
      status_quo: "Statu quo",
      trust: "Confianza",
      other: "Otra",
    },
    kindObjection: "Objeción",
    kindObstacle: "Obstáculo",
    kindUnknown: "Sin clasificar",
    resolutionResolved: "Resuelta",
    resolutionOpen: "Abierta",
    resolutionUnknown: "Sin dato",
    sampleLimited: "Con menos de cinco conversaciones no hay conclusión.",
    unavailable: "No disponible",
    briefNotReady: "El resumen todavía no está listo",
    briefReadFailed: "No se pudo leer el resumen",
    reportLoading: "Leyendo el informe",
    reportFailed: "No se pudo leer el informe",
    meetingReadFailed: "No se pudo leer la reunión",
    partialCrm: "Falta parte de los cierres del CRM",
  },
} as const;

export type ProductTranslations = (typeof productCatalog)["EN"];
