#!/usr/bin/env python3
"""
Dump the LIVE public schema (Supabase/Postgres) so it can be diffed by hand
against what's versioned in backend/migrations/ and backend/full_reset.sql.

Git is the source of truth for schema (see docs/DATABASE_SCHEMA.md) - this
script is how you check that it actually still is, instead of assuming it.
Drift happens (see docs/DATABASE_SCHEMA.md for the divergences already found
this way): a column's type, default or nullability can be changed by hand in
the Supabase dashboard and nothing in git will ever show it.

Preference order:
  1. DATABASE_URL (direct Postgres connection, e.g. via `psql` connection
     string): full dump, including CHECK constraints and real column
     defaults, via information_schema.columns and pg_constraint. Written to
     backend/migrations/_schema_dump.sql (gitignored - it's a point-in-time
     snapshot to compare against git, never something to commit).
  2. SUPABASE_URL + SUPABASE_SERVICE_ROLE_KEY (PostgREST OpenAPI doc):
     columns, types and nullability only - PostgREST's OpenAPI schema does
     not reliably expose CHECK constraints or real column defaults. Prints
     what it got to stdout, then prints the exact SQL to run by hand in the
     Supabase SQL editor to get the rest.
  3. Neither configured: exits cleanly with a message on stderr, no
     stack trace - this must be safe to run in CI or a fresh dev checkout
     without credentials.

Usage:
    python backend/scripts/dump_schema.py
"""

from __future__ import annotations

import json
import os
import sys
import urllib.request
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
OUTPUT_PATH = REPO_ROOT / "backend" / "migrations" / "_schema_dump.sql"

# Keep these in sync with docs/DATABASE_SCHEMA.md - they're the two queries
# documented there as "how to check for drift".
COLUMNS_QUERY = """
SELECT table_name, column_name, ordinal_position, data_type, udt_name,
       is_nullable, column_default, character_maximum_length
FROM information_schema.columns
WHERE table_schema = 'public'
ORDER BY table_name, ordinal_position;
""".strip()

CONSTRAINTS_QUERY = """
SELECT conname, pg_get_constraintdef(oid)
FROM pg_constraint
WHERE connamespace = 'public'::regnamespace
ORDER BY conname;
""".strip()


def _load_dotenv() -> None:
    """Best-effort load of backend/.env without requiring python-dotenv."""
    env_path = REPO_ROOT / "backend" / ".env"
    if not env_path.exists():
        return
    for line in env_path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        os.environ.setdefault(key.strip(), value.strip())


def dump_via_database_url(database_url: str) -> bool:
    try:
        import psycopg2  # type: ignore
    except ImportError:
        print(
            "DATABASE_URL is set but psycopg2 isn't installed (it's not in "
            "requirements.txt on purpose - this script is a dev tool, not a "
            "production dependency). Install it locally to use this path:\n"
            "  pip install psycopg2-binary\n"
            "Falling back to PostgREST...",
            file=sys.stderr,
        )
        return False

    try:
        conn = psycopg2.connect(database_url)
    except Exception as e:
        print(f"Could not connect with DATABASE_URL: {e}", file=sys.stderr)
        return False

    try:
        with conn, conn.cursor() as cur:
            cur.execute(COLUMNS_QUERY)
            columns = cur.fetchall()
            column_names = [d.name for d in cur.description]
            cur.execute(CONSTRAINTS_QUERY)
            constraints = cur.fetchall()
    except Exception as e:
        print(f"Query failed: {e}", file=sys.stderr)
        return False
    finally:
        conn.close()

    lines = [
        "-- Auto-generated by backend/scripts/dump_schema.py. DO NOT COMMIT.",
        "-- Point-in-time snapshot of the LIVE public schema.",
        "-- Compare this against backend/migrations/ + backend/full_reset.sql by hand -",
        "-- this file is evidence, not a migration and not a source of truth.",
        "",
        "-- information_schema.columns",
        " | ".join(column_names),
    ]
    for row in columns:
        lines.append(" | ".join("" if v is None else str(v) for v in row))
    lines.append("")
    lines.append("-- pg_constraint (pg_get_constraintdef)")
    lines.append("conname | definition")
    for conname, definition in constraints:
        lines.append(f"{conname} | {definition}")

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text("\n".join(lines) + "\n")
    print(f"Wrote {len(columns)} columns and {len(constraints)} constraints to {OUTPUT_PATH}")
    return True


def dump_via_postgrest(supabase_url: str, service_role_key: str) -> bool:
    base = supabase_url.rstrip("/")
    req = urllib.request.Request(
        f"{base}/rest/v1/",
        headers={
            "apikey": service_role_key,
            "Authorization": f"Bearer {service_role_key}",
        },
    )
    try:
        with urllib.request.urlopen(req, timeout=15) as resp:
            spec = json.loads(resp.read())
    except Exception as e:
        print(f"Could not reach PostgREST OpenAPI doc at {base}/rest/v1/: {e}", file=sys.stderr)
        return False

    definitions = spec.get("definitions", {})
    if not definitions:
        print("PostgREST OpenAPI doc returned no table definitions - nothing to dump.", file=sys.stderr)
        return False

    print(f"# Schema via PostgREST OpenAPI ({len(definitions)} tables) - columns/types/nullability only.\n")
    for table_name in sorted(definitions):
        table = definitions[table_name]
        required = set(table.get("required", []))
        props = table.get("properties", {})
        print(f"## {table_name}")
        for col_name in sorted(props):
            col = props[col_name]
            col_type = col.get("format") or col.get("type", "unknown")
            nullable = "NOT NULL" if col_name in required else "nullable"
            default = col.get("default")
            default_str = f" default={default!r}" if default is not None else ""
            print(f"  {col_name}: {col_type} ({nullable}){default_str}")
        print()

    print(
        "PostgREST doesn't reliably expose CHECK constraints or real column defaults.\n"
        "To get those (and to double check the above), run this in the Supabase SQL\n"
        "editor and paste the result back to whoever asked for this dump:\n\n"
        f"{COLUMNS_QUERY}\n\n"
        "-- and --\n\n"
        f"{CONSTRAINTS_QUERY}\n"
    )
    return True


def main() -> int:
    _load_dotenv()

    database_url = os.environ.get("DATABASE_URL")
    if database_url:
        if dump_via_database_url(database_url):
            return 0

    supabase_url = os.environ.get("SUPABASE_URL")
    service_role_key = os.environ.get("SUPABASE_SERVICE_ROLE_KEY")
    if supabase_url and service_role_key:
        if dump_via_postgrest(supabase_url, service_role_key):
            return 0
        return 1

    print(
        "No DATABASE_URL and no SUPABASE_URL/SUPABASE_SERVICE_ROLE_KEY found in the "
        "environment or backend/.env. Set one of them (see backend/.env.example) and "
        "re-run - this script does nothing else without credentials.",
        file=sys.stderr,
    )
    return 1


if __name__ == "__main__":
    sys.exit(main())
