#!/usr/bin/env node
// One source (shared/tokens/tokens.json), one output per surface.
// Every output carries two layers:
//   1. the surface's own legacy names, in the format it already consumes
//        web, desktop → HSL triplets, used as hsl(var(--x))   (Tailwind/shadcn)
//        extension    → full colors under its own names, used as var(--x)
//   2. the shared --v-* namespace (full colors), the only thing shared/ui/vocify-ui.css reads
// Usage: node scripts/build-tokens.mjs [--check]
//   --check exits 1 when a generated file is missing or stale (CI).
// VOCIFY_DESKTOP_DIR overrides where the desktop app lives (sibling repo).
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HEADER = '/* Generated by scripts/build-tokens.mjs from shared/tokens/tokens.json. Do not edit by hand. */\n';

export function renderTarget(tokens, target) {
  const lines = [];
  if (target.format === 'color') {
    for (const [name, key] of Object.entries(target.names)) {
      const value = tokens.color[key];
      if (value == null) throw new Error(`Unknown color token "${key}" for --${name}`);
      lines.push(`  --${name}: hsl(${value});`);
    }
  } else {
    for (const [name, value] of Object.entries(tokens.color)) lines.push(`  --${name}: ${value};`);
    for (const [name, value] of Object.entries(tokens.radius ?? {})) lines.push(`  --radius-${name}: ${value};`);
  }
  for (const [name, value] of Object.entries(tokens.color)) lines.push(`  --v-${name}: hsl(${value});`);
  for (const [name, value] of Object.entries(tokens.radius ?? {})) lines.push(`  --v-radius-${name}: ${value};`);
  return `${HEADER}:root {\n${lines.join('\n')}\n}\n`;
}

function resolveTargetPath(root, key, target, env) {
  if (key === 'desktop' && env.VOCIFY_DESKTOP_DIR) return join(resolve(root, env.VOCIFY_DESKTOP_DIR), 'renderer/tokens.css');
  return join(root, target.file);
}

export function buildAll({ root, check = false, env = process.env }) {
  const tokens = JSON.parse(readFileSync(join(root, 'shared/tokens/tokens.json'), 'utf8'));
  const report = { written: [], stale: [], skipped: [] };
  for (const [key, target] of Object.entries(tokens.targets)) {
    const file = resolveTargetPath(root, key, target, env);
    if (target.optional && !existsSync(dirname(file))) {
      report.skipped.push(key);
      continue;
    }
    const css = renderTarget(tokens, target);
    const current = existsSync(file) ? readFileSync(file, 'utf8') : null;
    if (current === css) continue;
    if (check) {
      report.stale.push(key);
      continue;
    }
    mkdirSync(dirname(file), { recursive: true });
    writeFileSync(file, css);
    report.written.push(key);
  }
  return report;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
  const check = process.argv.includes('--check');
  const report = buildAll({ root, check });
  for (const key of report.skipped) console.warn(`tokens: skipped ${key} (target folder not found)`);
  if (check && report.stale.length) {
    console.error(`tokens: stale → ${report.stale.join(', ')}. Run: node scripts/build-tokens.mjs`);
    process.exit(1);
  }
  if (!check) console.log(report.written.length ? `tokens: wrote ${report.written.join(', ')}` : 'tokens: up to date');
}
